name: publish
on:
  push:
    branches:
      - master
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: publish
        run: |
          podman login --username pureblue-os --password ${{ secrets.GH_PAT }} ghcr.io
          podman build . --tag ghcr.io/pureblue-os/pureblue:latest --build-arg SETUP_SCRIPT=base
          podman push ghcr.io/pureblue-os/pureblue:latest
