name: publish
on:
  push:
    branches:
      - master
concurrency:
  group: publish-queue-group
  cancel-in-progress: false
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Organization Name
        run: |
          echo "Setting the organization name..."
          echo "ORG_NAME=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "Organization Name set to: ${{ github.repository_owner }}"
      - name: Login to GHCR
        run: |
          echo "Logging into GHCR..."
          podman login --username $ORG_NAME --password ${{ secrets.GH_PAT }} ghcr.io
          echo "Login to GHCR successful"
      - name: Build and Push Images
        run: |
          ./build.sh --publish
